### ISSUE TITLE
Linking commands (&&) doesn't return correct exit code.

### ISSUE THREAD

**Issue by reggi** [vesln/nixt#13]
This assertion does not work as expected, it throws an error.

```javascript
it('should return exit code 1', function (done) {
  return nixt()
  .run('node -e \'process.exit(0)\' && node -e \'process.exit(1)\'')
  .code(1)
  .end(done)
})
```

```
AssertionError: `node -e 'process.exit(0)' && node -e 'process.exit(1)'`: Expected exit code: "1", actual: "0"
```

**Comment by reggi** [comment]
npm's default test expression breaks too.

```
it('should return exit code 1', function (done) {
  return nixt()
  .run('echo \"Error: no test specified\" && exit 1')
  .code(0)
  .end(done)
})
```

**Comment by reggi** [comment]
Also can't run `exit`.

```js
it('should return exit 1', function (done) {
  return nixt()
  .run('exit 1')
  .code(0)
  .end(done)
})
```

`Uncaught Error: spawn exit ENOENT`

**Comment by vesln** [comment]
lmk if you wanna try to investigate & provide a patch, happy to give contributor/npm access

**Comment by eush77** [comment]
@reggi `&&` and `exit` aren't actually supposed to work.

`nixt` uses [child_process.spawn][spawn] to spawn a process, not [child_process.exec][exec]. The difference between the two is that [spawn] simply starts a new process with the given arguments, and [exec] spawns a shell process (`/bin/sh` or `cmd.exe`) and passes the command to that shell. The latter is substantially different, because the shell language usually includes many things such as sequencing operators (e.g. `&&` and `||`), stdio redirection, loops and conditionals, built-in commands (e.g. `exit`) and so on.

Do you still need to be able to use shell operators or builtins with `nixt`? If so, what is your use case?

[spawn]: https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options
[exec]: https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

**Comment by eush77** [comment]
Closing due to lack of response.
